### ISSUE TITLE
What is these parameter?

### ISSUE THREAD

**Issue by CAI23sbP** [avidbots/flatland#102]
I saw thses parameter in map.world.yaml
`position_iterations` & `velocity_iterations`.
what are they?
When they are setting 0& 0 , then robot and other obstacle is not slip? or there is no friction in the simulator?

**Comment by josephduchesne** [comment]
Those two parameters are the configurations of the physics engine (box2d), as mentioned in the docs:
https://flatland-simulator.readthedocs.io/en/latest/core_functions/world.html

Documentation on what that does here:

https://box2d.org/documentation/md__d_1__git_hub_box2d_docs_hello.html#:~:text=The%20suggested%20iteration%20count%20for,increases%20performance%20but%20accuracy%20suffers.

Basically, lower numbers of iterations will run faster, but the physics simulation will be less accurate since the solver iteratively tries to satisfy all constraints, but  when two or more objects collide those constraints conflict with eachother. The iterative solver tries to solve each one in each loop, converging on the a more accurate solution.

Friction can be set on the footprints of models:

https://flatland-simulator.readthedocs.io/en/latest/core_functions/models.html?highlight=friction

The friction set there will apply a counteracting force each timestep towards zero motion based on the friction parameter.
