### ISSUE TITLE
Laser scan Clockwise or Counterclockwise?

### ISSUE THREAD

**Issue by sudo-Boris** [avidbots/flatland#80]
Is the scan generated and then interpreted clockwise or counterclockwise?
When training a model with flatland, the evaluation in the simulation is great, but when deploying onto the turtlebot3, the robot doesn't do what it should. The assumption is that the scan data is not interpreted correctly.
The turtlebot3 generates its scan data counterclockwise.

**Comment by josephduchesne** [comment]
I believe it's clockwise by default, however this branch adds a "flipped" parameter (as well as some performance improvements) to the laser scan plugin: https://github.com/avidbots/flatland/pull/79

It's not merged into the mainline yet due to automatic CI tests failing, despite the tests passing on my local machine. I haven't had a chance to dig deeper into the CI test issue, but I think the branch works fine.

**Comment by josephduchesne** [comment]
The laser scan "flipped" parameter is now part of the mainline.
